backend {
  default = "Local"
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        concurrent-job-limit = 2
        run-in-background = true
        runtime-attributes = """
          Int? cpu
          String? docker
          Int? gpuCount
        """
     	submit-docker = """
      docker run \
          --rm -i \
          ${if defined(gpuCount) then "--gpus all" else ""} \
          -v ${cwd}:${docker_cwd} \
          ${docker} ${job_shell} ${docker_cwd}/execution/script
      """
      }
    }
  }
}
